### ISSUE TITLE
Update of Go test runner

### ISSUE THREAD

**Issue by tehsphinx** [exercism/go-test-runner#10]
@iHiD [Latest commit](https://github.com/exercism/go-test-runner/commit/a4d1f06fe5ec6a9f66fce151ff228649cf0f6dbf) updates the Go test runner to capture compile error messages.

@ccare can you update the Go test runner? Let me know if you want version tags, PRs, or some other workflow for updating the test runner.

**Comment by tehsphinx** [comment]
FYI @ErikSchierboom

**Comment by tehsphinx** [comment]
Sample output on cases when `go test` itself fails.

### compilation error
```json
{
	"status": "error",
	"tests": [
		{
			"name": "build",
			"status": "error",
			"expected": "",
			"actual": "",
			"message": "./sample_test.go:37:1: missing return at end of function"
		}
	]
}
```
### non-standard-library package imported
```
{
	"status": "error",
	"tests": [
		{
			"name": "build",
			"status": "error",
			"expected": "",
			"actual": "",
			"message": "package _/solution (test)\n\timports github.com/pkg/errors: cannot find package \"github.com/pkg/errors\" in any of:\n\t/usr/local/go/src/github.com/pkg/errors (from $GOROOT)\n\t/go/src/github.com/pkg/errors (from $GOPATH)"
		}
	]
}
```

**Comment by iHiD** [comment]
Thanks @tehsphinx. This will get merged/deployed on Monday.

**Comment by ErikSchierboom** [comment]
Sweet
