### ISSUE TITLE
Go  - Tests passing for solutions that don't compile

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go-test-runner#35]
I noticed that for some solutions I'm mentoring, there's the little icon at the top saying the tests passed but the solutions don't even compile. I noticed this on the Go track on 2 different exercises, there might be happening in more.

@exercism/go
@ErikSchierboom

**Comment by ErikSchierboom** [comment]
Using @bobahop's sample code, I can confirm that there is indeed a bug in the test runner. I copied the above code into the stub of the scrabble score exercise, and then ran `go test` locally:

```
erik@VELPIE:~/exercism/go/exercises/practice/scrabble-score$ go test
can't load package: package scrabble: 
scrabble_score.go:5:14: expected ';', found ','
```

I then ran the test runner using `./bin/run-in-docker.sh scrabble-score /home/erik/exercism/go/exercises/practice/scrabble-score /home/erik/exercism/go/exercises/practice/scrabble-score`, which output the following `results.json` file:

```json
{
	"status": "pass",
	"version": 2,
	"tests": []
}
```

CC @tehsphinx

**Comment by bobahop** [comment]
Also, the bottom line here

```go
func Score(word string) int {

. . .

word := strings.ToUpper(word)
```

generates the error

```
no new variables on left side of :=
```

**Comment by moshegood** [comment]
`go test` will return 1 on build failures too.
We need to differentiate the two causes of failure.
I can put up a PR later today.

**Comment by ErikSchierboom** [comment]
@moshegood Brilliant! That would be much appreciated

**Comment by moshegood** [comment]
https://github.com/exercism/go-test-runner/pull/36/files

**Comment by ErikSchierboom** [comment]
@bobahop @andrerfcsantos A new version of the test runner has been released that fixes this (courtesy of @moshegood). Would you mind testing it, and if it works, close this issue?

**Comment by andrerfcsantos** [comment]
I think this is working now. I did a quick test and the tests now fail for solutions that don't compile. I also haven't seen this problem anymore in students solutions. I'll close this issue. Feel free to add additional commentaries or re-open the issue if necessary.

**Comment by iHiD** [comment]
Thanks for updating!
