### ISSUE TITLE
Integrate Go Test Runner in Exercism

### ISSUE THREAD

**Issue by tehsphinx** [exercism/go-test-runner#4]
The Go test runner is ready to be integrated in exercism.

See the [Readme](https://github.com/exercism/go-test-runner) for details.

**Comment by tehsphinx** [comment]
Big thanks to @SeventhNadir who has done a big part of the work on the test runner!

**Comment by josh-helios** [comment]
@tehsphinx thanks for taking the time to get me started on the path!

**Comment by iHiD** [comment]
Thanks both! 

@ccare will get this setup. We'll have an interface to start testing this soon too. My aim is that we can put something out there for you to play with by the end of this week.

**Comment by iHiD** [comment]
@tehsphinx  If you add a comment on https://github.com/exercism/automated-tests/issues/32 then this issue can be closed :)
