### ISSUE TITLE
Issue with special characters in output message

### ISSUE THREAD

**Issue by junedev** [exercism/go-test-runner#42]
Quotes in the output message are not displayed correctly anymore. Might be related to #41 (not sure how though).

Example (see last line)
```
# lasagna [lasagna.test]
./lasagna_test.go:39:14: undefined: RemainingOvenTime
FAIL	lasagna [build failed]
&#39;/usr/local/go/bin/go test --short --json .&#39; returned exit code 2: exit status 2
```

**Comment by jmrunkle** [comment]
This does not appear to be just you. It seemed to be happening on other analyzers as well (for example, the Java track).

**Comment by junedev** [comment]
@ErikSchierboom @iHiD Was there any change recently on how the test runner output message is displayed that could explain this?

**Comment by ErikSchierboom** [comment]
@junedev Could be [this PR]9https://github.com/exercism/website/pull/1886).

**Comment by iHiD** [comment]
I've reverted that in https://github.com/exercism/website/pull/1993 - we're double escaping now.

**Comment by junedev** [comment]
@iHiD Was the fix deployed? The bug described in this ticket is still visible.

**Comment by iHiD** [comment]
See https://github.com/exercism/exercism/issues/5985#issuecomment-932136992

**Comment by junedev** [comment]
Understood. Its fixed now. :tada:

**Comment by iHiD** [comment]
Great! Just finished deploying 🦜
