### ISSUE TITLE
`elons-toys` getting error fetching go-cmp

### ISSUE THREAD

**Issue by jmrunkle** [exercism/go-test-runner#43]
Here is the error message:

> go: github.com/google/go-cmp@v0.5.3: Get &quot;https://proxy.golang.org/github.com/google/go-cmp/@v/v0.5.3.mod&quot;: dial tcp: lookup proxy.golang.org on 10.0.2.3:53: dial udp 10.0.2.3:53: connect: network is unreachable
&#39;/usr/local/go/bin/go test --short --json .&#39; returned exit code 1: exit status 1

This occurs even when copy-pasting [the exemplar solution](https://raw.githubusercontent.com/exercism/go/main/exercises/concept/elons-toys/.meta/exemplar.go) into the web editor and running the tests.

**Comment by jmrunkle** [comment]
I cannot find any reason why it would be trying to contact the network... I cannot find anything special about elons-cars that would trigger this.

**Comment by junedev** [comment]
I cannot reproduce this. Can you try again and see whether you still get the error?

![image](https://user-images.githubusercontent.com/12543047/134977886-ce3996a0-1902-44ba-a59c-22a8dcf3ce49.png)

**Comment by junedev** [comment]
The only scenario I see is that a student imported that package and submitted this (maybe even incl. the new go.mod via CLI) and the test runner got compromised somehow into thinking that package is still needed for the next test run. Test runners are recycled over night so if there was a problem, it might be gone by now.

**Comment by jmrunkle** [comment]
> @jmrunkle Are you using an updated version of the exercise? The `go.mod` for this exercise did have this dependency, but that was fixed with https://github.com/exercism/go/pull/1535.
> 
> The only reason I see this happening is it is using an old version of the exercise. But updating the exercise should fix it.

I even tried reverting the exercise to the base then pasting the exemplar solution. No dice. Maybe resetting to base does not reset the base files like go.mod?

**Comment by andrerfcsantos** [comment]
If you do `exercism download --exercise=elons-toys --track=go --force`, which `go.mod` do you get?

**Comment by jmrunkle** [comment]
> If you do `exercism download --exercise=elons-toys --track=go --force`, which `go.mod` do you get?

I am not using the CLI, this is entirely through the web UI. It may not be a problem with the test runner at all, this could be that the web UI provides no way to reset those auxiliary files.

**Comment by jmrunkle** [comment]
OK, something appears to have changed because I just reloaded the exercise changed nothing (added a space) and re-ran the tests and they pass now. I do not doubt that the issue was a pre-existing go.mod issue, I was just concerned that there seemed to be no way to complete this in the web UI. Something appears to have triggered an update to the exercise (perhaps the introduction changed or something like that). In any case, it is working now so I can go ahead and close this.
