### ISSUE TITLE
Test order should not be randomized

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/go-test-runner#46]
I noticed that on every test run I am getting a slightly different test order. This might be fine for practice exercise (or not, I think that depends on the track), but it's not fine for concept exercises IMO. Those are meant to be solved task by task, so I always expect the test failures to be ordered by task. The tests for this exercise are ordered by task. It's the test runner that randomizes their order.

## Run 1

![Screenshot 2021-10-02 at 19-18-47 Exercism](https://user-images.githubusercontent.com/7852553/135726338-5778701c-5d10-4144-b24b-0788e2d6edc5.png)

## Run 2
![Screenshot 2021-10-02 at 19-19-13 Exercism](https://user-images.githubusercontent.com/7852553/135726339-de54ab7c-a5c3-4d00-893a-685c2dabe2de.png)

PS: There is a different issue visible on those screenshot (no tests for `CalculateProductionRatePerMinute`). I will debug/report that separately.

**Comment by junedev** [comment]
I am working on the fix.
